### ISSUE TITLE
I get an array error

### ISSUE THREAD

**Issue by Abbas-Muneer** [MrJavaScripty/Android#1]
I keep getting an error every time I try run the week 03 dog breed tutorial.
The steps that I followed was I coded the same thing as same as it was on this repo.
The error I get is:
"java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.tutorial_03/com.example.tutorial_03.MainActivity}: java.lang.IllegalArgumentException: Random range is empty: [0, -1)."

**Comment by MrJavaScripty** [comment]
@Abbas-Muneer Did you follow the steps in the README ?

**Comment by Abbas-Muneer** [comment]
Dear Sir,
I sorted out the issue sir, sorry for the inconvenience.

Regards,
Abbas
